server:
  port: 8081
spring:
  r2dbc:
    url: r2dbc:postgres://kmvckmre:p-Xur4NdDzV7L-V6rk_rEQVw_68WIJaV@satao.db.elephantsql.com:5432/kmvckmre
    name: kmvckmre
    username: kmvckmre
    password: p-Xur4NdDzV7L-V6rk_rEQVw_68WIJaV
  data:
    r2dbc:
      repositories:
        enabled: true
  rsocket:
    server:
      transport: TCP
      port: 9090
  devtools:
    livereload:
      port: 35730
      enabled: true
